# -*- coding: utf-8 -*-
"""Declarative page definitions for build.py (service child pages)."""
from build import (BASE, page_hero, signs_section, process_section, table_section,
                   pricing_section, feature_section, gallery_section, faq_section,
                   related_section, area_callout, cta_banner,
                   service_schema, breadcrumb, faqpage)

def crumbs(name, slug):
    return [("Home", "/"), ("Services", "/services/"), (name, None)]

PAGES = []

# ===================================================================== DECK & PATIO STAINING
_deck_faq = [
 ("How often should I restain my deck in Florida?",
  "In Tampa Bay’s climate, most decks need restaining every 2-3 years for semi-transparent stains, and every 3-5 years for solid stains. Clear sealers may need reapplication annually. The frequency depends on sun exposure, foot traffic, and the quality of the original application."),
 ("Can you stain a deck that has already been painted?",
  "Yes, but it requires stripping the existing paint first. Paint sits on top of wood and prevents stain penetration. We can strip the old paint, prep the surface, and apply a stain finish. This is more labor-intensive but achieves a better long-term result."),
 ("What is the difference between stain and sealer?",
  "A sealer provides moisture protection but minimal color. Stain provides both color and protection. Semi-transparent stains show wood grain while adding color; solid stains hide the grain entirely. For Florida, we typically recommend semi-transparent stain with UV inhibitors for the best balance of protection and appearance."),
 ("How long does deck staining take?",
  "A typical residential deck takes 2-3 days total: one day for washing and prep, 48-72 hours of drying time, then one day for stain application. Larger or more damaged decks may take an additional day. Weather can extend the timeline if rain occurs during the drying window."),
]
PAGES.append(dict(
  slug="services/deck-patio-staining",
  title="Deck & Patio Staining Riverview FL | Ayala Pro Painting",
  description="Professional deck & patio staining in Riverview, FL. UV-resistant stains & sealers for Florida conditions. Restore and protect your outdoor spaces. Free estimates!",
  canonical=f"{BASE}/services/deck-patio-staining/",
  schemas=[
    service_schema("Deck and Patio Staining", "Professional deck and patio staining and sealing services in Riverview, FL.", f"{BASE}/services/deck-patio-staining/", "Deck Staining"),
    breadcrumb([("Home", "/"), ("Services", "/services/"), ("Deck & Patio Staining", f"{BASE}/services/deck-patio-staining/")]),
    faqpage(_deck_faq)],
  body="\n\n".join([
    page_hero("Outdoor Living", "Deck &amp; Patio Staining Services in Riverview, FL",
      "Ayala Pro Painting provides professional deck and patio staining services for homeowners in Riverview, Florida and south Hillsborough County. Florida&rsquo;s intense UV radiation, afternoon thunderstorms, and year-round humidity make outdoor wood surfaces especially vulnerable to fading, cracking, mildew, and premature aging. Our deck staining process includes thorough power washing, wood brightening, sanding, and application of premium UV-resistant stains and sealers that protect your investment and extend the life of your outdoor living spaces. Every project includes owner oversight and our workmanship warranty.",
      crumbs("Deck & Patio Staining", "deck-patio-staining")),
    signs_section("Signs You Need This Service", "Is Your Deck Showing Signs of Florida Weather Damage?",
      "Florida&rsquo;s climate is particularly harsh on outdoor wood surfaces. If your deck or patio shows any of these signs, professional staining and sealing can restore its beauty and protect it from further damage:",
      ["Gray, weathered appearance &mdash; the natural wood color has faded to a dull silver-gray",
       "Splintering or rough texture making barefoot walking uncomfortable or unsafe",
       "Green or black mildew/algae growth, especially in shaded areas",
       "Peeling or flaking from previous stain that was improperly applied or has deteriorated",
       "Water absorption &mdash; water soaks into the wood rather than beading on the surface",
       "Cracking or splitting boards from UV damage and moisture cycling"],
      "Weathered backyard deck being stained in Riverview, FL"),
    process_section("How We Stain and Seal Your Deck", [
      ("Inspection &amp; Assessment", "We evaluate your deck&rsquo;s wood type, condition, existing finish, and structural integrity. We identify boards needing replacement and recommend the right stain type."),
      ("Power Washing", "Professional-grade pressure washing removes dirt, mildew, algae, loose paint, and old stain. We use appropriate PSI for each wood type to clean without damaging the grain."),
      ("Wood Brightening", "Apply wood brightener to restore the wood&rsquo;s natural pH balance after pressure washing. This opens the grain for optimal stain absorption and brings back the warm wood tone."),
      ("Sanding &amp; Prep", "Sand rough spots, splinters, and raised grain. Replace any damaged boards. Tape off adjacent surfaces. Allow wood to dry completely (48-72 hours after washing)."),
      ("Stain/Sealer Application", "Apply your chosen stain or sealer using brush, roller, or spray technique appropriate for the product. We work with the grain and maintain a wet edge for uniform coverage."),
      ("Second Coat &amp; Inspection", "For semi-transparent and solid stains, apply a second coat after appropriate drying time. Final inspection for coverage uniformity, drips, and missed spots."),
    ]),
    table_section("Products &amp; Materials", "Stain &amp; Sealer Products We Recommend",
      "We select stain and sealer products based on your wood type, desired appearance, and the level of UV/moisture protection needed for Florida conditions.",
      ["Product / Brand", "Details", "Why We Use It"], [
      ["Sherwin-Williams", "SuperDeck, WoodScapes", "Excellent UV resistance, waterproofing, and color retention. Transparent, semi-transparent, and solid options."],
      ["Benjamin Moore", "Arborcoat", "Premium exterior stain with advanced UV and moisture protection. Superior color depth and penetration."],
      ["Specialty Sealers", "Thompson&rsquo;s WaterSeal, Defy Extreme, Ready Seal", "Penetrating sealers for maximum water repellency. Ready Seal is oil-based and self-priming for easy maintenance coats."],
      ], anchor="products"),
    pricing_section("How Much Does Deck Staining Cost in Riverview, FL?",
      "Deck staining costs depend on deck size, condition, product choice, and the amount of prep work required.", [
      ["Small Deck (under 200 sq ft)", "$400 &ndash; $800", "Size, condition, product type"],
      ["Medium Deck (200-400 sq ft)", "$800 &ndash; $1,500", "Most common size in Riverview"],
      ["Large Deck (400+ sq ft)", "$1,500 &ndash; $3,000+", "Multi-level, complex railings"],
      ["Fence Staining (per linear ft)", "$3 &ndash; $8 / lin ft", "Height, condition, product"],
      ["Pergola / Gazebo", "$500 &ndash; $1,500", "Size and detail level"],
      ["Stain Stripping (add-on)", "$2 &ndash; $4 / sq ft", "Required when removing old solid stain"],
      ], "Prices shown are estimates for typical Riverview-area projects. Your quote will be based on a free on-site assessment."),
    feature_section("Why Choose Us", "Why Choose Ayala Pro Painting for Deck Staining?", [
      ("Proper Dry Time", "We allow 48-72 hours after washing before staining. Rushing this step is the #1 cause of deck stain failure."),
      ("Right Product for Your Wood", "Pressure-treated pine, cedar, redwood, and composite each require different products. We match the stain to your wood type."),
      ("Florida UV Protection", "Every product we use includes UV inhibitors specifically rated for Florida&rsquo;s extreme sun exposure."),
      ("Complete Prep Included", "Power wash, brighten, sand, and repair are all included in our pricing. No surprise add-on charges for preparation."),
      ("Maintenance Guidance", "We provide written care instructions and recommend a maintenance schedule to maximize the life of your stain."),
    ]),
    gallery_section("Deck &amp; Patio Projects in Riverview", [
      ("Deck Staining", "Riverview, FL", "Freshly stained wood deck in a Riverview FL backyard"),
      ("Fence Staining", "Valrico, FL", "Stained privacy fence in Valrico FL"),
      ("Pergola Refinishing", "Fish Hawk, FL", "Stained pergola over a patio in Fish Hawk FL"),
    ]),
    faq_section("Deck Staining Questions", _deck_faq),
    related_section("You Might Also Need", [
      ("/services/pressure-washing/", "Pressure Washing", "Clean every surface the right way before staining or as a standalone service."),
      ("/services/exterior-painting/", "Exterior Painting", "UV- and weather-rated coatings with our 7-step prep process."),
      ("/services/garage-floor-epoxy/", "Garage Floor Epoxy", "Durable, chemical-resistant coatings for a showroom-quality garage floor."),
    ]),
    area_callout("Deck Staining Across South Hillsborough County"),
    cta_banner("Ready to Restore Your Outdoor Living Space?", "Get a free, no-obligation deck staining estimate from Riverview&rsquo;s trusted professionals."),
  ]),
))

# ===================================================================== GARAGE FLOOR EPOXY
_epoxy_faq = [
 ("How long does epoxy floor installation take?",
  "Most residential garages take 2-3 days: day 1 for grinding, repair, and primer; day 2 for epoxy base coat and flake broadcast; day 3 for topcoat. You can walk on the floor after 24 hours and park on it after 72 hours. Total garage downtime is typically 3-5 days."),
 ("Will epoxy work on my cracked garage floor?",
  "Yes, in most cases. We repair cracks with flexible polyurea filler before applying epoxy. However, if the slab has significant structural issues, active settling, or severe moisture problems, we’ll identify those during our assessment and discuss options before proceeding."),
 ("Why does DIY epoxy peel off?",
  "The three most common causes of DIY epoxy failure are: inadequate surface preparation (acid etching instead of diamond grinding), moisture vapor transmission from below the slab (no moisture barrier), and using thin water-based products that can’t withstand hot tire pickup or chemical exposure."),
 ("Can you coat a patio or pool deck with epoxy?",
  "Outdoor surfaces typically require different coating systems than garage epoxy, as they need UV resistance and slip resistance when wet. We offer concrete coatings suitable for outdoor applications including patios, pool decks, and walkways. Contact us to discuss the best system for your outdoor surface."),
]
PAGES.append(dict(
  slug="services/garage-floor-epoxy",
  title="Garage Floor Epoxy Riverview FL | Ayala Pro Painting",
  description="Professional garage floor epoxy & coatings in Riverview, FL. Durable, chemical-resistant finishes that transform your garage. Multiple styles available. Free estimates!",
  canonical=f"{BASE}/services/garage-floor-epoxy/",
  schemas=[
    service_schema("Garage Floor Epoxy Coating", "Professional garage floor epoxy and concrete coating services in Riverview, FL.", f"{BASE}/services/garage-floor-epoxy/", "Epoxy Floor Coating"),
    breadcrumb([("Home", "/"), ("Services", "/services/"), ("Garage Floor Epoxy", f"{BASE}/services/garage-floor-epoxy/")]),
    faqpage(_epoxy_faq)],
  body="\n\n".join([
    page_hero("Specialty Coatings", "Garage Floor Epoxy &amp; Coatings in Riverview, FL",
      "Ayala Pro Painting installs professional garage floor epoxy and concrete coatings for homeowners in Riverview, Florida and south Hillsborough County. Our garage floor systems transform bare, stained, or deteriorating concrete into durable, chemical-resistant, and visually striking surfaces. We offer multiple coating systems including decorative flake, solid color, and metallic epoxy options, all engineered to resist hot tire pickup, oil stains, and the moisture common in Florida garages. Professional installation includes diamond grinding, crack repair, moisture testing, and multi-layer application for a finish that lasts 10-15 years.",
      crumbs("Garage Floor Epoxy", "garage-floor-epoxy")),
    signs_section("Signs You Need This Service", "Is Your Garage Floor Cracked, Stained, or Embarrassing?",
      "Most Florida garage floors are uncoated concrete that degrades over time. If your garage floor shows any of these conditions, a professional epoxy coating can transform it:",
      ["Oil stains, rust marks, and chemical spills that won&rsquo;t clean up",
       "Cracks, spalling, or pitting from concrete degradation and moisture",
       "Dusty surface that tracks concrete dust into your home",
       "Hot tire marks from parked vehicles lifting the concrete surface",
       "Previous DIY epoxy that is peeling, bubbling, or flaking off",
       "You want to convert your garage into a functional workspace, gym, or showroom"],
      "Epoxy-coated garage floor with decorative flake finish in Riverview, FL"),
    process_section("How We Install Your Epoxy Floor", [
      ("Concrete Assessment", "Evaluate slab condition, moisture levels (calcium chloride test), cracks, and previous coatings. Determine if the concrete can accept epoxy or needs repair first."),
      ("Diamond Grinding", "Mechanically grind the entire surface with diamond-tipped equipment to create the profile needed for epoxy adhesion. This is the critical step that separates professional installs from DIY failures."),
      ("Crack &amp; Spall Repair", "Fill cracks with flexible polyurea filler, repair spalled areas with concrete patch, and level any uneven spots. These repairs are invisible under the final coating."),
      ("Primer / Moisture Barrier", "Apply a penetrating primer that bonds to the concrete and blocks moisture vapor transmission. Florida&rsquo;s high water table makes this step essential for long-term adhesion."),
      ("Base Coat Application", "Apply the colored epoxy base coat across the entire surface. For flake systems, broadcast decorative chips into the wet base coat for a textured, multi-color finish."),
      ("Clear Topcoat", "Apply a UV-resistant polyaspartic or polyurethane clear topcoat for abrasion resistance, chemical protection, and a glossy or satin finish. This is what makes the floor durable for 10-15 years."),
    ]),
    table_section("Products &amp; Materials", "Epoxy &amp; Coating Systems We Install",
      "We install professional-grade coating systems that outperform hardware store DIY kits by 5-10x in durability and adhesion.",
      ["Product / System", "Details", "Why We Use It"], [
      ["100% Solids Epoxy", "Base coat system", "Zero-solvent, maximum thickness and durability. 3-5x thicker than water-based DIY kits. Chemical and abrasion resistant."],
      ["Polyaspartic Topcoat", "UV-resistant clear coat", "Cures faster than traditional polyurethane, superior UV resistance (won&rsquo;t yellow), excellent chemical resistance. Industry standard topcoat."],
      ["Decorative Flake", "Broadcast chip system", "Vinyl flake chips broadcast into wet epoxy for a textured, multi-color finish. Hides imperfections and provides anti-slip texture."],
      ], anchor="products"),
    pricing_section("How Much Does Garage Floor Epoxy Cost in Riverview?",
      "Professional epoxy flooring costs more than DIY kits but lasts 5-10x longer and won&rsquo;t peel. Here are typical costs for Riverview-area garages.", [
      ["1-Car Garage (200-250 sq ft)", "$1,500 &ndash; $2,500", "Standard flake or solid color system"],
      ["2-Car Garage (400-500 sq ft)", "$2,500 &ndash; $4,500", "Most common Riverview garage size"],
      ["3-Car Garage (600-750 sq ft)", "$4,000 &ndash; $6,500", "Larger footprint, more materials"],
      ["Metallic Epoxy (per sq ft)", "$8 &ndash; $15 / sq ft", "Premium swirled metallic finish"],
      ["Crack/Spall Repair (add-on)", "$200 &ndash; $800", "Depending on severity and extent"],
      ["Previous Coating Removal", "$2 &ndash; $4 / sq ft", "Required if old epoxy/paint is peeling"],
      ], "Prices shown are estimates for typical Riverview-area projects. Your quote will be based on a free on-site assessment."),
    feature_section("Why Choose Us", "Why Choose Professional Epoxy Over DIY Kits?", [
      ("Diamond Grinding vs. Acid Etch", "DIY kits use acid etching which provides weak adhesion. We diamond grind for a mechanical bond 3-5x stronger."),
      ("100% Solids vs. Water-Based", "Our epoxy is 100% solids &mdash; 3-5x thicker than water-based hardware store kits. More material means more durability."),
      ("Moisture Testing", "Florida&rsquo;s high water table causes DIY epoxy to peel within months. We test moisture levels and apply vapor barriers when needed."),
      ("UV-Resistant Topcoat", "Our polyaspartic topcoat won&rsquo;t yellow from UV exposure through garage windows or open doors. DIY kits yellow within 1-2 years."),
      ("10-15 Year Lifespan", "Professional systems last 10-15 years. DIY kits typically last 2-4 years before peeling. The math favors professional installation."),
    ]),
    gallery_section("Garage Floor Projects in Riverview &amp; Tampa Bay", [
      ("Flake Epoxy Garage", "Riverview, FL", "Decorative flake epoxy garage floor in Riverview FL"),
      ("Metallic Epoxy", "Brandon, FL", "Metallic epoxy garage floor in Brandon FL"),
      ("Solid Color Coating", "Apollo Beach, FL", "Solid color epoxy garage floor in Apollo Beach FL"),
    ]),
    faq_section("Garage Floor Epoxy Questions", _epoxy_faq),
    related_section("You Might Also Need", [
      ("/services/pressure-washing/", "Pressure Washing", "Professional surface cleaning for driveways, decks, and exteriors."),
      ("/services/deck-patio-staining/", "Deck &amp; Patio Staining", "Premium stains and sealers for your outdoor living spaces."),
      ("/services/interior-painting/", "Interior Painting", "Refresh the rest of your home with clean, lasting interior finishes."),
    ]),
    area_callout("Garage Floor Epoxy Across South Hillsborough County"),
    cta_banner("Ready for a Garage Floor You&rsquo;re Proud Of?", "Get a free, no-obligation epoxy flooring estimate from Riverview&rsquo;s trusted professionals."),
  ]),
))

# ===================================================================== DRYWALL REPAIR
_dry_faq = [
 ("Can you match my existing wall texture?",
  "Yes. We match all common Florida wall textures including orange peel (the most common in Riverview’s newer homes), knockdown, smooth, skip trowel, and hand-textured finishes. We apply texture to the repaired area and feather it into the surrounding surface for a seamless blend."),
 ("Do you repair water-damaged drywall?",
  "Yes, once the source of water intrusion has been resolved. We remove damaged drywall, check for mold (and refer to a mold remediation specialist if found), install new drywall, and finish to match. We do not repair water damage if the leak or moisture source has not been fixed."),
 ("Is drywall repair included in your painting services?",
  "Minor repairs (nail pops, small holes, hairline cracks) are included in our standard painting preparation at no additional charge. Larger repairs requiring new drywall sections or extensive patching are quoted separately but at a discounted rate when bundled with a painting project."),
 ("How long does drywall repair take?",
  "Small repairs (nail pops, small holes) can be completed in a few hours. Larger patches or multiple repairs in a room typically take 1-2 days due to drying time between compound coats. Full wall sections or ceiling work may take 2-3 days."),
]
PAGES.append(dict(
  slug="services/drywall-repair",
  title="Drywall Repair Riverview FL | Ayala Pro Painting",
  description="Professional drywall repair & texture matching in Riverview, FL. Holes, cracks, water damage, and texture restoration. Seamless results. Free estimates!",
  canonical=f"{BASE}/services/drywall-repair/",
  schemas=[
    service_schema("Drywall Repair and Texture Matching", "Professional drywall repair, patching, and texture matching services in Riverview, FL.", f"{BASE}/services/drywall-repair/", "Drywall Repair"),
    breadcrumb([("Home", "/"), ("Services", "/services/"), ("Drywall Repair", f"{BASE}/services/drywall-repair/")]),
    faqpage(_dry_faq)],
  body="\n\n".join([
    page_hero("Wall Restoration", "Drywall Repair &amp; Texture Matching in Riverview, FL",
      "Ayala Pro Painting provides professional drywall repair and texture matching services for homeowners in Riverview, Florida and south Hillsborough County. Whether you have nail pops, small holes, large patches, water damage, stress cracks, or texture that needs matching, our team restores your walls and ceilings to a seamless, paint-ready finish. We handle everything from minor touch-ups to full wall sections, matching your existing texture so repairs blend invisibly with the surrounding surface. Drywall repair is included in our painting services or available as a standalone service.",
      crumbs("Drywall Repair", "drywall-repair")),
    signs_section("Signs You Need This Service", "Does Your Drywall Need Professional Attention?",
      "Drywall damage ranges from minor cosmetic issues to structural concerns. Professional repair ensures invisible results that DIY patches rarely achieve:",
      ["Nail or screw pops creating small bumps or circles visible through paint",
       "Holes from doorknobs, anchors, accidents, or removed fixtures",
       "Cracks along seams, corners, or around windows and doors from settling",
       "Water stains or soft/bubbling drywall from leaks or humidity damage",
       "Mismatched texture from previous amateur repairs that stand out",
       "Popcorn ceiling removal leaving uneven surfaces needing finishing"],
      "Smooth, repaired drywall section ready for paint in Riverview, FL"),
    process_section("How We Repair Your Drywall", [
      ("Damage Assessment", "Evaluate the type and extent of damage. Identify the cause (settling, moisture, impact) to ensure the repair addresses the root issue, not just the symptom."),
      ("Removal &amp; Prep", "Cut out damaged drywall, remove loose material, and prepare the area for patching. For water damage, we ensure the moisture source is resolved before proceeding."),
      ("Patching &amp; Taping", "Install new drywall sections or apply appropriate patch materials. Tape all joints with paper or mesh tape and apply initial coats of joint compound."),
      ("Mudding &amp; Sanding", "Apply multiple thin coats of joint compound, sanding between each coat for a smooth, flat surface. This step requires patience and skill for invisible results."),
      ("Texture Matching", "Match the existing wall or ceiling texture (orange peel, knockdown, smooth, skip trowel, etc.) so the repair blends seamlessly with the surrounding surface."),
      ("Prime &amp; Paint", "Prime the repaired area and paint to match the surrounding wall. We color-match the existing paint to ensure a uniform finish."),
    ]),
    table_section("Products &amp; Materials", "Materials We Use for Drywall Repair",
      "Quality drywall repair depends on using the right materials for each type of damage.",
      ["Product / Brand", "Details", "Why We Use It"], [
      ["Joint Compound", "USG Sheetrock, ProForm", "Lightweight setting compounds for faster drying and reduced shrinkage. Multiple thin coats for professional results."],
      ["Drywall Tape", "Paper tape, FibaFuse mesh", "Paper tape for corners and high-stress joints. Mesh tape for flat seams and small repairs."],
      ["Patch Materials", "California Patch, metal patches, new drywall sections", "Size-appropriate patching for everything from small nail holes to large wall sections."],
      ], anchor="products"),
    pricing_section("How Much Does Drywall Repair Cost in Riverview?",
      "Drywall repair costs vary based on the type and size of damage. Most repairs are quick and affordable.", [
      ["Small Holes (nail/screw pops, &lt;2 in)", "$75 &ndash; $150 each", "Quick patch, texture match, paint touch-up"],
      ["Medium Holes (2-6 inches)", "$150 &ndash; $300 each", "Cut-in patch, tape, mud, texture, paint"],
      ["Large Patches (6+ in to full panels)", "$300 &ndash; $800+", "New drywall section, full finishing"],
      ["Water Damage Repair", "$400 &ndash; $1,500+", "Depends on extent; may require mold remediation referral"],
      ["Ceiling Repair", "$200 &ndash; $600", "Height premium, overhead work, texture matching"],
      ["Popcorn Ceiling Removal (per room)", "$500 &ndash; $1,200", "Scrape, skim coat, finish to smooth or new texture"],
      ], "Prices shown are estimates for typical Riverview-area projects. Your quote will be based on a free on-site assessment."),
    feature_section("Why Choose Us", "Why Choose Ayala Pro Painting for Drywall Repair?", [
      ("Invisible Repairs", "Our multi-coat process and texture matching make repairs genuinely invisible. You won&rsquo;t be able to find the patch when we&rsquo;re done."),
      ("Texture Expertise", "We match orange peel, knockdown, smooth, skip trowel, and other common Florida textures. Getting texture right separates professional from amateur work."),
      ("Paint-Ready Finish", "Every repair is primed and painted to match your existing walls. We don&rsquo;t leave you with a white patch on a colored wall."),
      ("Bundled With Painting", "Drywall repair is included as part of our painting preparation. If you&rsquo;re already getting rooms painted, repairs come at a reduced rate."),
      ("Root Cause Awareness", "We identify why the damage occurred. If it&rsquo;s a settling crack that will reopen, we use flexible compounds. If it&rsquo;s moisture, we flag the source."),
    ]),
    gallery_section("Drywall Repair Projects in Riverview", [
      ("Wall Patch &amp; Texture", "Riverview, FL", "Invisible drywall patch with matched texture in Riverview FL"),
      ("Ceiling Repair", "Brandon, FL", "Repaired and retextured ceiling in Brandon FL"),
      ("Popcorn Removal", "Valrico, FL", "Popcorn ceiling removed and finished smooth in Valrico FL"),
    ]),
    faq_section("Drywall Repair Questions", _dry_faq),
    related_section("You Might Also Need", [
      ("/services/interior-painting/", "Interior Painting", "Repaired walls deserve a fresh, flawless coat of premium paint."),
      ("/services/exterior-painting/", "Exterior Painting", "UV- and weather-rated coatings with our 7-step prep process."),
      ("/services/cabinet-painting/", "Cabinet Painting", "Factory-smooth cabinet refinishing in any color you choose."),
    ]),
    area_callout("Drywall Repair Across South Hillsborough County"),
    cta_banner("Ready to Restore Your Walls?", "Get a free, no-obligation drywall repair estimate from Riverview&rsquo;s trusted professionals."),
  ]),
))

# ===================================================================== COLOR CONSULTATION
_color_faq = [
 ("Is color consultation really free with a painting project?",
  "Yes. When you book any painting project with Ayala Pro Painting, color consultation is included at no additional charge. We want you to love your colors, and professional guidance ensures you will."),
 ("How long does a color consultation take?",
  "A typical consultation takes 1-2 hours for the in-home assessment and style discussion. We then develop palette options within 24-48 hours. The sample viewing period adds another 1-2 days. Total process: 3-5 days from first visit to final selections."),
 ("Can you match a color I saw online or in a magazine?",
  "Yes. We can match virtually any color from any source — a photo, a fabric swatch, a magazine page, or a digital image. Our Sherwin-Williams and Benjamin Moore color-matching systems provide accurate formulations for any color you provide."),
 ("What if I don't like the colors after they're on the wall?",
  "Our large-sample process is specifically designed to prevent this. By seeing real paint samples in your actual lighting for 24-48 hours before committing, you’ll know exactly how the color will look before we paint. If you’re still uncertain, we can apply additional samples at no charge."),
]
PAGES.append(dict(
  slug="services/color-consultation",
  title="Paint Color Consultation Riverview FL | Ayala Pro Painting",
  description="Expert paint color consultation in Riverview, FL. We help you choose perfect colors for your home's interior & exterior. Complimentary with painting services!",
  canonical=f"{BASE}/services/color-consultation/",
  schemas=[
    service_schema("Paint Color Consultation", "Expert paint color consultation services for homeowners in Riverview, FL.", f"{BASE}/services/color-consultation/", "Color Consultation"),
    breadcrumb([("Home", "/"), ("Services", "/services/"), ("Color Consultation", f"{BASE}/services/color-consultation/")]),
    faqpage(_color_faq)],
  body="\n\n".join([
    page_hero("Design Services", "Paint Color Consultation in Riverview, FL",
      "Ayala Pro Painting offers expert paint color consultation for homeowners in Riverview, Florida who want professional guidance choosing the perfect colors for their interior or exterior painting project. Choosing paint colors can feel overwhelming with thousands of options available. Our consultation service takes the guesswork out of color selection by evaluating your home&rsquo;s lighting, existing decor, architectural style, and personal preferences to recommend a cohesive color palette that transforms your space. Color consultation is complimentary for all painting project clients.",
      crumbs("Color Consultation", "color-consultation")),
    signs_section("Signs You Need This Service", "Overwhelmed by Paint Color Choices?",
      "Choosing paint colors is one of the most stressful parts of a painting project for most homeowners. Common challenges include:",
      ["Thousands of color options creating decision paralysis",
       "Colors looking different in the store versus on your walls at home",
       "Undertones (pink, green, yellow) appearing unexpectedly in certain lighting",
       "Difficulty visualizing a color covering an entire room versus a small swatch",
       "Coordinating colors between rooms, trim, ceilings, and exterior elements",
       "Wanting to update your look but unsure what styles suit your home&rsquo;s architecture"],
      "Paint swatches and color fan decks on a table in Riverview, FL"),
    process_section("How Our Color Consultation Works", [
      ("In-Home Assessment", "We visit your home to evaluate natural and artificial lighting, existing furniture and decor, flooring, countertops, and architectural features that influence color selection."),
      ("Style Discussion", "We discuss your preferences: warm or cool tones, bold or subtle, modern or traditional. We look at inspiration images and discuss the mood you want each room to convey."),
      ("Palette Development", "Based on our assessment, we develop 2-3 coordinated color palette options using Sherwin-Williams and Benjamin Moore color systems. Each palette includes wall, trim, ceiling, and accent colors."),
      ("Large Samples", "We apply large-format paint samples (12x12 inch minimum) directly on your walls so you can see each color in your actual lighting conditions throughout the day."),
      ("Final Selection", "After living with the samples for 24-48 hours and seeing them in different light, we finalize your color choices and confirm the complete palette for your project."),
    ]),
    table_section("Color Systems &amp; Tools", "Color Systems &amp; Tools We Use",
      "We work with industry-leading color systems to ensure accurate, repeatable color selection.",
      ["Product / Tool", "Details", "Why We Use It"], [
      ["Sherwin-Williams ColorSnap", "Digital + physical fan decks", "1,700+ colors, color-matching technology, Visualizer app for digital previews."],
      ["Benjamin Moore Color Portfolio", "Fan decks + large samples", "1,500+ colors, known for truest color accuracy from swatch to wall."],
      ["Large-Format Samples", "Peel-and-stick or painted samples", "12x12&quot; minimum samples applied directly to your walls for real-world evaluation."],
      ], anchor="products"),
    pricing_section("Color Consultation Pricing",
      "Color consultation is designed to be accessible for every homeowner.", [
      ["With Painting Project", "Complimentary", "Included at no charge with any painting project booking"],
      ["Standalone Consultation (1-3 rooms)", "$150 &ndash; $250", "In-home visit, palette development, large samples"],
      ["Whole-Home Consultation", "$300 &ndash; $500", "Complete interior/exterior palette, room-by-room coordination"],
      ["Exterior Color Selection", "$150 &ndash; $250", "Body, trim, door, shutter, and accent color recommendations"],
      ], "Prices shown are estimates for typical Riverview-area projects. Your quote will be based on a free on-site assessment."),
    feature_section("Why Choose Us", "Why Professional Color Consultation?", [
      ("We See Undertones", "Every white has an undertone (pink, blue, green, yellow). We identify which undertones work with your fixed elements like flooring, countertops, and furniture."),
      ("Lighting Matters", "A color that looks perfect in a south-facing room may look completely different in a north-facing room. We evaluate every room&rsquo;s lighting conditions."),
      ("Cohesive Flow", "Open floor plans need colors that flow naturally from room to room. We create palettes that maintain visual harmony throughout your home."),
      ("Save Money on Mistakes", "Repainting because you chose the wrong color costs time and money. Getting it right the first time is what consultation delivers."),
      ("Florida-Specific Knowledge", "Riverview&rsquo;s abundant natural light affects how colors read. We know which colors thrive in Florida&rsquo;s bright, warm light versus looking washed out."),
    ]),
    gallery_section("Color Consultation Results", [
      ("Living Room Palette", "Riverview, FL", "Coordinated living room color palette in Riverview FL"),
      ("Whole-Home Scheme", "Fish Hawk, FL", "Whole-home color scheme in Fish Hawk FL"),
      ("Exterior Color Selection", "Apollo Beach, FL", "Exterior body, trim, and door color selection in Apollo Beach FL"),
    ]),
    faq_section("Color Consultation Questions", _color_faq),
    related_section("You Might Also Need", [
      ("/services/interior-painting/", "Interior Painting", "Bring your chosen palette to life with premium interior finishes."),
      ("/services/exterior-painting/", "Exterior Painting", "UV- and weather-rated coatings with our 7-step prep process."),
      ("/services/cabinet-painting/", "Cabinet Painting", "Factory-smooth cabinet refinishing in your perfect color."),
    ]),
    area_callout("Color Consultation Across South Hillsborough County"),
    cta_banner("Ready to Find Your Perfect Colors?", "Book a painting project and your color consultation is complimentary. Get your free estimate today."),
  ]),
))

# ===================================================================== INTERIOR PAINTING (authored from template)
_int_faq = [
 ("How much does interior painting cost in Riverview, FL?",
  "Interior painting in Riverview typically ranges from $300-$800 per room and $2,500-$5,500 for a full 3-bedroom home, depending on room count, ceiling height, wall condition, and the number of coats required. Pricing includes preparation, primer, two coats of premium paint, and complete cleanup. Contact us for a free, detailed estimate."),
 ("How long does it take to paint a home interior?",
  "A single room is usually completed in a day. A full interior repaint of a 3-bedroom home typically takes 3-5 days depending on the scope, the amount of trim and detail work, and drying time between coats. We confirm your timeline in writing before we start."),
 ("What kind of paint do you use for Florida interiors?",
  "We use premium low-VOC interior paints from Sherwin-Williams and Benjamin Moore, including mildew-resistant formulations for bathrooms, kitchens, and laundry rooms where Florida humidity is highest. Low-VOC products mean minimal odor so you can return to your space sooner."),
 ("Do I need to move my furniture before you paint?",
  "We handle most of the heavy lifting. We move and cover furniture, protect your floors, and tape off trim and fixtures. We simply ask that you remove small personal items, wall decor, and fragile belongings from the rooms being painted."),
]
PAGES.append(dict(
  slug="services/interior-painting",
  title="Interior Painting Riverview FL | Ayala Pro Painting",
  description="Professional interior painting in Riverview, FL. Walls, ceilings, trim, doors & accent walls with low-VOC, humidity-resistant finishes. Licensed & insured. Free estimates!",
  canonical=f"{BASE}/services/interior-painting/",
  schemas=[
    service_schema("Interior House Painting", "Professional interior house painting services in Riverview, FL and south Hillsborough County.", f"{BASE}/services/interior-painting/", "Interior Painting"),
    breadcrumb([("Home", "/"), ("Services", "/services/"), ("Interior Painting", f"{BASE}/services/interior-painting/")]),
    faqpage(_int_faq)],
  body="\n\n".join([
    page_hero("Interior Painting", "Interior House Painting in Riverview, FL",
      "Ayala Pro Painting delivers professional interior house painting for homeowners throughout Riverview, Florida and south Hillsborough County. From a single accent wall to a whole-home repaint, we paint walls, ceilings, trim, doors, and cabinets with meticulous preparation and premium, low-VOC, humidity-resistant finishes built for Florida living. Every project includes thorough surface prep, careful protection of your floors and furniture, owner oversight by Eliseo Ayala, and a written 2-year workmanship warranty. Call today for your free, no-obligation interior painting estimate.",
      crumbs("Interior Painting", "interior-painting")),
    signs_section("What We Paint", "Transform Every Room in Your Home",
      "Interior painting does more than refresh a color &mdash; it protects your walls, brightens your space, and adds real value to your home. Our interior services include:",
      ["Walls and ceilings in any room, from bedrooms to open-concept living areas",
       "Trim, baseboards, crown molding, doors, and door frames",
       "Accent and feature walls to add depth and personality",
       "Kitchens, bathrooms, and laundry rooms with mildew-resistant paint",
       "Hallways, stairwells, and high-ceiling spaces",
       "Repainting after a move, renovation, or to cover years of wear"],
      "Freshly painted interior living room by Ayala Pro Painting in Riverview, FL"),
    process_section("Our Interior Painting Process", [
      ("Free Estimate &amp; Color Help", "Eliseo visits your home, measures the space, discusses colors and finishes, and delivers a detailed, itemized estimate within 24-48 hours."),
      ("Protection &amp; Prep", "We move and cover furniture, mask floors, trim, and fixtures, then patch nail holes, fill cracks, sand glossy surfaces, and caulk gaps for a flawless base."),
      ("Priming", "We spot-prime repairs and stains &mdash; or full-prime when changing colors dramatically &mdash; so your topcoat is even, true, and long-lasting."),
      ("Two-Coat Application", "We apply two coats of premium paint with crisp cut-in lines and smooth, roller-mark-free walls, working room by room to keep your home livable."),
      ("Cleanup &amp; Walkthrough", "We remove all materials, reset your furniture, and walk every room with you to confirm you love the result before we consider the job done."),
    ]),
    table_section("Products &amp; Materials", "Interior Paints We Recommend",
      "We select interior products based on the room, the surface, and Florida&rsquo;s humidity.",
      ["Product / Brand", "Details", "Why We Use It"], [
      ["Sherwin-Williams", "Emerald, Cashmere", "Exceptional coverage and a smooth, durable, washable finish that resists scuffs and stains."],
      ["Benjamin Moore", "Aura, Regal Select", "Rich color depth, low-VOC formulation, and excellent hide &mdash; ideal for color changes in one or two coats."],
      ["Bath &amp; Kitchen", "Mildew-resistant low-VOC enamels", "Moisture- and mildew-resistant finishes formulated for Florida&rsquo;s most humid rooms."],
      ], anchor="products"),
    pricing_section("How Much Does Interior Painting Cost in Riverview?",
      "Interior painting costs depend on room count, ceiling height, wall condition, and the number of coats required.", [
      ["Single Room (walls + ceiling)", "$300 &ndash; $800", "Varies by room size, condition, and coats"],
      ["Full Interior (3BR home)", "$2,500 &ndash; $5,500", "Includes walls, ceilings, trim, and doors"],
      ["Trim &amp; Doors (per room)", "$150 &ndash; $400", "Baseboards, casings, crown, and doors"],
      ["Accent / Feature Wall", "$150 &ndash; $350", "Single wall, includes prep and two coats"],
      ["Ceiling Painting (per room)", "$200 &ndash; $500", "Flat or textured, height dependent"],
      ], "Prices shown are estimates for typical Riverview-area projects. Your quote will be based on a free on-site assessment."),
    feature_section("Why Choose Us", "Why Riverview Homeowners Choose Us for Interior Painting", [
      ("Owner on Every Job", "Eliseo personally oversees your project from estimate through the final walkthrough."),
      ("Spotless, Respectful Work", "We protect your floors and furniture, clean up daily, and treat your home like our own."),
      ("Low-VOC, Low-Odor", "Premium low-VOC paints mean minimal fumes so you can enjoy your space sooner."),
      ("Crisp Lines, Smooth Walls", "Meticulous cut-in and two-coat application produce a clean, professional finish."),
      ("Written 2-Year Warranty", "Every interior project is backed by a written workmanship warranty."),
    ]),
    gallery_section("Interior Painting Projects in Riverview", [
      ("Living Room Repaint", "Riverview, FL", "Freshly painted living room interior in Riverview FL"),
      ("Bedroom &amp; Trim", "Brandon, FL", "Painted bedroom walls and trim in Brandon FL"),
      ("Whole-Home Interior", "Fish Hawk, FL", "Whole-home interior repaint in Fish Hawk FL"),
    ]),
    faq_section("Interior Painting Questions", _int_faq),
    related_section("You Might Also Need", [
      ("/services/cabinet-painting/", "Cabinet Painting", "Factory-smooth kitchen and bath cabinet refinishing in any color."),
      ("/services/drywall-repair/", "Drywall Repair", "Patch holes, fix cracks, and match textures before we paint."),
      ("/services/color-consultation/", "Color Consultation", "Expert help choosing colors that thrive in Florida light."),
    ]),
    area_callout("Interior Painting Across South Hillsborough County"),
    cta_banner("Ready to Refresh Your Interior?", "Get a free, no-obligation interior painting estimate from Riverview&rsquo;s trusted professionals."),
  ]),
))

# ===================================================================== EXTERIOR PAINTING (authored from template)
_ext_faq = [
 ("How much does exterior painting cost in Riverview, FL?",
  "Exterior painting in Riverview typically ranges from $3,000-$6,000 for a single-story home and $5,000-$10,000 for a two-story home, depending on size, surface condition, and prep required. Every estimate includes pressure washing, our full prep process, and two coats of premium, weather-rated paint."),
 ("How often should I repaint my home's exterior in Florida?",
  "In Tampa Bay’s climate, exterior repaints are typically needed every 5-7 years — sooner than the 7-10 years common in cooler, drier regions. Florida’s intense UV, humidity, salt air, and afternoon storms break paint down faster, which is why premium products and proper prep matter so much here."),
 ("What is your exterior prep process?",
  "Our 7-step prep is what makes our finishes last: power wash, scrape loose paint, sand, fill and repair, prime bare surfaces, caulk gaps and cracks, and protect landscaping and fixtures — all before a single finish coat goes on. Skipping prep is the #1 cause of premature paint failure in Florida."),
 ("Do you paint exteriors during Florida's rainy season?",
  "Yes, with smart scheduling. During summer we start early to maximize dry hours before afternoon storms and monitor forecasts daily. The dry season (October-April) is ideal for exterior work, and we never apply coatings to damp surfaces or when rain threatens the curing window."),
]
PAGES.append(dict(
  slug="services/exterior-painting",
  title="Exterior Painting Riverview FL | Ayala Pro Painting",
  description="Professional exterior house painting in Riverview, FL. UV- and weather-rated coatings with a 7-step prep process built for Florida. Licensed & insured. Free estimates!",
  canonical=f"{BASE}/services/exterior-painting/",
  schemas=[
    service_schema("Exterior House Painting", "Professional exterior house painting services in Riverview, FL and south Hillsborough County.", f"{BASE}/services/exterior-painting/", "Exterior Painting"),
    breadcrumb([("Home", "/"), ("Services", "/services/"), ("Exterior Painting", f"{BASE}/services/exterior-painting/")]),
    faqpage(_ext_faq)],
  body="\n\n".join([
    page_hero("Exterior Painting", "Exterior House Painting in Riverview, FL",
      "Ayala Pro Painting protects and beautifies homes throughout Riverview, Florida and south Hillsborough County with professional exterior house painting. Florida&rsquo;s sun, humidity, salt air, and seasonal storms are hard on exterior surfaces &mdash; so we pair premium, UV-resistant, weather-rated coatings with a thorough 7-step preparation process that makes our finishes last years longer. From stucco and siding to trim, doors, and fascia, every project includes owner oversight by Eliseo Ayala and a written 2-year workmanship warranty. Call today for your free, no-obligation exterior painting estimate.",
      crumbs("Exterior Painting", "exterior-painting")),
    signs_section("Signs It's Time to Repaint", "Is Florida Weather Wearing Down Your Home's Exterior?",
      "Florida&rsquo;s climate degrades exterior paint faster than almost anywhere in the country. If your home shows any of these signs, it&rsquo;s time for a professional repaint:",
      ["Fading, chalking, or a powdery residue on painted surfaces",
       "Peeling, cracking, or blistering paint, especially on sun-facing walls",
       "Mildew, mold, or green/black streaks on stucco and siding",
       "Bare wood, exposed stucco, or visible primer showing through",
       "Cracked or failing caulk around windows, doors, and trim",
       "You&rsquo;re preparing to sell, or your HOA has flagged your home&rsquo;s appearance"],
      "Two-story Florida home exterior freshly repainted in Riverview, FL"),
    process_section("Our 7-Step Exterior Painting Process", [
      ("Free Estimate &amp; Assessment", "Eliseo inspects your home&rsquo;s surfaces, identifies repairs, discusses colors, and delivers a detailed, itemized estimate within 24-48 hours."),
      ("Pressure Wash", "We pressure wash the entire exterior to remove dirt, chalk, mildew, and loose paint &mdash; included in every exterior project at no extra charge."),
      ("Scrape, Sand &amp; Repair", "We scrape and sand failing paint, repair damaged wood or stucco, and address the root causes of paint failure."),
      ("Caulk &amp; Prime", "We re-caulk gaps and cracks around trim, windows, and doors, and prime all bare and repaired surfaces for maximum adhesion."),
      ("Protect", "We mask and cover windows, fixtures, landscaping, and hardscapes so only the surfaces meant to be painted get painted."),
      ("Two-Coat Application", "We apply two coats of premium, UV- and weather-rated paint using the right technique for each surface, maintaining clean lines throughout."),
      ("Final Inspection &amp; Warranty", "We walk the entire exterior with you, touch up any detail on the spot, and back the work with a written warranty."),
    ]),
    table_section("Products &amp; Materials", "Exterior Paints We Recommend",
      "We select coatings engineered for Tampa Bay&rsquo;s UV, humidity, and storm exposure.",
      ["Product / Brand", "Details", "Why We Use It"], [
      ["Sherwin-Williams", "Duration, Emerald Exterior", "Outstanding UV resistance, color retention, and a flexible film that resists cracking and peeling in Florida heat."],
      ["Benjamin Moore", "Aura Exterior", "Premium fade- and mildew-resistant finish with exceptional durability and color depth."],
      ["Stucco &amp; Masonry", "Elastomeric &amp; masonry coatings", "Thick, waterproofing coatings that bridge hairline cracks and breathe &mdash; ideal for Florida stucco."],
      ], anchor="products"),
    pricing_section("How Much Does Exterior Painting Cost in Riverview?",
      "Exterior painting costs depend on home size, stories, surface type, and condition.", [
      ["Single-Story Home", "$3,000 &ndash; $6,000", "Includes prep, power wash, and 2 coats"],
      ["Two-Story Home", "$5,000 &ndash; $10,000", "Larger surface area and access requirements"],
      ["Trim &amp; Fascia Only", "$1,000 &ndash; $2,500", "Refresh trim without full body repaint"],
      ["Front Door / Shutters", "$150 &ndash; $400", "Accent refresh for instant curb appeal"],
      ["Stucco / Wood Repair (add-on)", "Varies", "Quoted after on-site assessment of damage"],
      ], "Prices shown are estimates for typical Riverview-area projects. Your quote will be based on a free on-site assessment."),
    feature_section("Why Choose Us", "Why Riverview Homeowners Choose Us for Exterior Painting", [
      ("7-Step Prep Process", "Proper preparation &mdash; not just paint &mdash; is why our exterior finishes last years longer in Florida."),
      ("Florida-Grade Coatings", "Premium UV- and mildew-resistant products formulated for Tampa Bay&rsquo;s sun, humidity, and salt air."),
      ("Pressure Washing Included", "Every exterior project starts with a professional pressure wash at no additional charge."),
      ("Weather-Smart Scheduling", "We plan around Florida&rsquo;s storms and never paint damp surfaces or beat the curing window."),
      ("Written 2-Year Warranty", "Every exterior project is backed by a written workmanship warranty."),
    ]),
    gallery_section("Exterior Painting Projects in Riverview", [
      ("Single-Story Repaint", "Riverview, FL", "Single-story home exterior repaint in Riverview FL"),
      ("Two-Story Stucco", "Valrico, FL", "Two-story stucco home exterior painting in Valrico FL"),
      ("Trim &amp; Door Refresh", "Apollo Beach, FL", "Exterior trim and front door refresh in Apollo Beach FL"),
    ]),
    faq_section("Exterior Painting Questions", _ext_faq),
    related_section("You Might Also Need", [
      ("/services/pressure-washing/", "Pressure Washing", "Professional surface cleaning &mdash; included with every exterior repaint."),
      ("/services/deck-patio-staining/", "Deck &amp; Patio Staining", "Protect your outdoor wood with premium UV-resistant stains."),
      ("/services/color-consultation/", "Color Consultation", "Choose body, trim, and door colors that shine in Florida light."),
    ]),
    area_callout("Exterior Painting Across South Hillsborough County"),
    cta_banner("Ready to Boost Your Curb Appeal?", "Get a free, no-obligation exterior painting estimate from Riverview&rsquo;s trusted professionals."),
  ]),
))

# ===================================================================== CABINET PAINTING (authored from template)
_cab_faq = [
 ("How much does cabinet refinishing cost in Riverview, FL?",
  "Professional kitchen cabinet refinishing in Riverview typically ranges from $3,500-$7,000, depending on the number of doors and drawers, the finish you choose, and any repairs needed. That’s a fraction of the $20,000+ cost of replacing cabinets — for a result that looks brand new."),
 ("How long does cabinet painting take?",
  "A typical kitchen takes 4-6 days from start to finish. This includes removing doors and hardware, cleaning and degreasing, sanding, priming, and applying multiple coats of durable enamel with proper cure time between coats. We keep your kitchen usable as much as possible during the project."),
 ("Is painted cabinetry durable?",
  "Yes. We use bonding primers and premium cabinet-grade urethane enamels (such as Sherwin-Williams Emerald Urethane and Benjamin Moore Advance) applied for a smooth, factory-like finish that resists chips, stains, and daily kitchen wear. Proper prep and the right products are what make the finish last."),
 ("Do I have to empty my cabinets before you start?",
  "Yes, please empty the contents of the cabinets being refinished so we can remove doors and drawers and work safely. We handle everything else — removing and labeling doors, protecting countertops and floors, and reinstalling hardware when the finish has cured."),
]
PAGES.append(dict(
  slug="services/cabinet-painting",
  title="Cabinet Painting Riverview FL | Ayala Pro Painting",
  description="Professional cabinet painting & refinishing in Riverview, FL. Factory-smooth durable finishes for kitchen & bath cabinets in any color. A fraction of replacement cost. Free estimates!",
  canonical=f"{BASE}/services/cabinet-painting/",
  schemas=[
    service_schema("Cabinet Painting and Refinishing", "Professional cabinet painting and refinishing services in Riverview, FL and south Hillsborough County.", f"{BASE}/services/cabinet-painting/", "Cabinet Refinishing"),
    breadcrumb([("Home", "/"), ("Services", "/services/"), ("Cabinet Painting", f"{BASE}/services/cabinet-painting/")]),
    faqpage(_cab_faq)],
  body="\n\n".join([
    page_hero("Cabinet Refinishing", "Cabinet Painting &amp; Refinishing in Riverview, FL",
      "Ayala Pro Painting gives kitchens and bathrooms a complete transformation with professional cabinet painting and refinishing for homeowners in Riverview, Florida and south Hillsborough County. For a fraction of the cost of replacement, we refinish your existing cabinets with a durable, factory-smooth finish in any color you choose. Our process &mdash; thorough degreasing, sanding, bonding primer, and premium cabinet-grade enamels applied with care &mdash; produces a hard, washable finish built to withstand daily kitchen use. Every project includes owner oversight by Eliseo Ayala and our workmanship warranty.",
      crumbs("Cabinet Painting", "cabinet-painting")),
    signs_section("Why Refinish Instead of Replace", "Love Your Layout, Hate Your Cabinet Color?",
      "If your cabinets are structurally sound but dated, refinishing delivers a dramatic transformation without the cost and disruption of replacement. Cabinet painting is the right choice when:",
      ["Your cabinet boxes and doors are solid but the color or finish is dated",
       "You want a modern white, gray, navy, or custom color kitchen",
       "Wood-tone or oak cabinets feel dark and out of style",
       "Replacement quotes ($20,000+) are far beyond your budget",
       "You&rsquo;re refreshing a kitchen or bath before selling your home",
       "You want a high-end, factory-smooth finish &mdash; not a brushed DIY look"],
      "White refinished kitchen cabinets by Ayala Pro Painting in Riverview, FL"),
    process_section("Our Cabinet Refinishing Process", [
      ("Free Estimate &amp; Color Help", "Eliseo evaluates your cabinets, discusses color and finish options, and delivers a detailed, itemized estimate within 24-48 hours."),
      ("Remove &amp; Label", "We remove and carefully label every door, drawer front, and piece of hardware so everything goes back exactly where it belongs."),
      ("Clean, Degrease &amp; Sand", "We thoroughly degrease and sand all surfaces &mdash; the critical step that lets the new finish bond and last in a hard-working kitchen."),
      ("Bonding Primer", "We apply a high-adhesion bonding primer so the enamel grips slick or previously finished surfaces and resists chipping."),
      ("Spray-Applied Enamel", "We apply multiple coats of premium cabinet-grade urethane enamel for a smooth, durable, factory-like finish with no brush marks."),
      ("Reassembly &amp; Walkthrough", "Once cured, we reinstall doors, drawers, and hardware, then walk the finished kitchen with you to confirm you love the result."),
    ]),
    table_section("Products &amp; Materials", "Cabinet Finishes We Recommend",
      "Cabinet finishes take more abuse than walls, so we use hard, washable, cabinet-grade products.",
      ["Product / Brand", "Details", "Why We Use It"], [
      ["Sherwin-Williams", "Emerald Urethane Trim Enamel", "Hard, smooth, furniture-quality finish that resists chips, stains, and daily kitchen wear."],
      ["Benjamin Moore", "Advance", "Waterborne alkyd enamel that levels to a smooth, durable, factory-like finish with low odor."],
      ["Bonding Primer", "High-adhesion bonding primers", "Grips slick, glossy, or previously finished cabinets so the enamel bonds and lasts."],
      ], anchor="products"),
    pricing_section("How Much Does Cabinet Refinishing Cost in Riverview?",
      "Cabinet refinishing costs depend on the number of doors and drawers, the finish chosen, and any repairs needed.", [
      ["Kitchen (standard)", "$3,500 &ndash; $7,000", "Typical Riverview kitchen, doors + drawers + boxes"],
      ["Kitchen + Island", "$5,000 &ndash; $9,000", "Adds island and additional cabinetry"],
      ["Bathroom Vanity", "$600 &ndash; $1,500", "Single vanity, doors and drawer fronts"],
      ["Glaze / Specialty Finish (add-on)", "+$500 &ndash; $1,500", "Glazing, distressing, or custom finishes"],
      ], "Prices shown are estimates for typical Riverview-area projects. Your quote will be based on a free on-site assessment."),
    feature_section("Why Choose Us", "Why Riverview Homeowners Choose Us for Cabinet Refinishing", [
      ("Factory-Smooth Finish", "Spray-applied cabinet-grade enamel produces a smooth, hard finish with no brush or roller marks."),
      ("A Fraction of Replacement", "Get a brand-new look for a fraction of the $20,000+ cost of replacing cabinets."),
      ("Proper Prep That Lasts", "Degreasing, sanding, and bonding primer are what keep the finish from chipping in a busy kitchen."),
      ("Any Color You Want", "From classic white to bold custom colors &mdash; matched precisely with our color systems."),
      ("Owner Oversight &amp; Warranty", "Eliseo oversees every cabinet project, backed by our written workmanship warranty."),
    ]),
    gallery_section("Cabinet Refinishing Projects in Riverview", [
      ("White Kitchen Refinish", "Riverview, FL", "White refinished kitchen cabinets in Riverview FL"),
      ("Navy Island", "Fish Hawk, FL", "Navy painted kitchen island in Fish Hawk FL"),
      ("Bathroom Vanity", "Brandon, FL", "Refinished bathroom vanity in Brandon FL"),
    ]),
    faq_section("Cabinet Painting Questions", _cab_faq),
    related_section("You Might Also Need", [
      ("/services/interior-painting/", "Interior Painting", "Pair new cabinets with fresh walls, ceilings, and trim."),
      ("/services/color-consultation/", "Color Consultation", "Expert help choosing the perfect cabinet and wall colors."),
      ("/services/drywall-repair/", "Drywall Repair", "Patch and texture-match walls before your kitchen refresh."),
    ]),
    area_callout("Cabinet Refinishing Across South Hillsborough County"),
    cta_banner("Ready to Transform Your Kitchen?", "Get a free, no-obligation cabinet refinishing estimate from Riverview&rsquo;s trusted professionals."),
  ]),
))

# ===================================================================== COMMERCIAL CHILDREN
# Authored from the commercial-hub guide context + service-page template (no dedicated docx).
COM_HUB = "/services/commercial-painting/"
def com_crumbs(name, url):
    return ([("Home", "/"), ("Services", "/services/"), ("Commercial Painting", COM_HUB), (name, None)],
            [("Home", "/"), ("Services", "/services/"), ("Commercial Painting", f"{BASE}{COM_HUB}"), (name, url)])

# --------------------------------------------------------------- Commercial Interior
_ci_crumbs_hero, _ci_crumbs_schema = com_crumbs("Interior Commercial Painting", f"{BASE}/services/commercial-interior/")
_ci_faq = [
 ("Can you paint our offices after business hours?",
  "Yes. We routinely schedule commercial interior painting for evenings, overnights, and weekends so your business stays open and your team and customers are never disrupted. We coordinate building access, security protocols, and alarm systems with your management in advance."),
 ("Do you use low-odor paint for occupied spaces?",
  "Yes. For occupied offices, retail, and medical spaces we use low-VOC and zero-VOC products that meet indoor air quality standards, so there are no lingering fumes affecting your staff, customers, or patients."),
 ("How do you minimize disruption to our operations?",
  "We work in phases, isolate work areas with protection and signage, paint during off-peak hours, and keep clean, clearly marked work zones. You get a written schedule up front and a single point of contact in Eliseo throughout the project."),
 ("Do you provide a certificate of insurance for our building?",
  "Absolutely. We carry $1 million in general liability and full workers' compensation coverage and provide certificates of insurance to your property manager, landlord, or building management at no additional charge."),
]
PAGES.append(dict(
  slug="services/commercial-interior",
  title="Commercial Interior Painting Riverview FL | Ayala Pro Painting",
  description="Commercial interior painting in Riverview, FL for offices, retail, medical & restaurants. Low-VOC products, after-hours scheduling, minimal disruption. Free estimates!",
  canonical=f"{BASE}/services/commercial-interior/",
  schemas=[
    service_schema("Interior Commercial Painting", "Professional interior commercial painting for offices, retail, medical, and restaurants in Riverview, FL.", f"{BASE}/services/commercial-interior/", "Commercial Interior Painting"),
    breadcrumb(_ci_crumbs_schema), faqpage(_ci_faq)],
  body="\n\n".join([
    page_hero("Commercial Painting", "Interior Commercial Painting in Riverview, FL",
      "Ayala Pro Painting provides professional interior commercial painting for offices, retail stores, medical facilities, restaurants, and professional spaces throughout Riverview, Florida and the greater Tampa Bay area. We understand that a commercial interior repaint has to happen on your schedule, not ours &mdash; so we work after hours and on weekends, use low-VOC products that keep your space usable, and protect your fixtures, inventory, and equipment throughout. With flexible scheduling, commercial-grade finishes, and the personal accountability of an owner-operated company, we deliver a professional result with minimal disruption. Call for a free commercial estimate.",
      _ci_crumbs_hero, phone_first=True),
    signs_section("Where We Work", "Professional Interiors for Every Kind of Business",
      "From a single lobby refresh to a full retail buildout, our interior commercial painting covers the spaces your customers and team see every day:",
      ["Offices, lobbies, conference rooms, and common areas",
       "Retail floors, boutiques, salons, and showrooms",
       "Medical and dental offices with low-VOC, sanitary finishes",
       "Restaurants, dining rooms, and back-of-house (kitchen-safe coatings)",
       "Tenant improvements and lease-turnover repaints",
       "Warehouses, breakrooms, restrooms, and corridors"],
      "Freshly painted commercial office interior in Riverview, FL", bg="white"),
    process_section("Our Commercial Interior Process", [
      ("Walkthrough &amp; Estimate", "We tour your space, document scope and access constraints, recommend products, and deliver a written estimate within 48 hours."),
      ("Schedule Around You", "We build the schedule around your hours &mdash; evenings, overnights, weekends, or phased zones &mdash; so your operations keep running."),
      ("Protect &amp; Prep", "We protect furniture, electronics, inventory, and flooring, then patch, sand, and prime surfaces for a clean, lasting finish."),
      ("Low-VOC Application", "We apply commercial-grade, low-odor coatings with crisp lines and even coverage, keeping work zones clean and clearly marked."),
      ("Inspection &amp; Handover", "We walk the finished space with your point of contact, touch up any detail on the spot, and provide warranty documentation."),
    ]),
    table_section("Our Approach", "Built for Occupied Commercial Spaces",
      "Everything about our interior process is designed to keep your business open and your space presentable throughout.",
      ["Priority", "How We Deliver It"], [
      ["Minimal Disruption", "After-hours and phased scheduling so customers and staff are never inconvenienced."],
      ["Indoor Air Quality", "Low-VOC and zero-VOC products that meet occupied-space standards &mdash; no lingering fumes."],
      ["Brand Consistency", "Exact brand-color matching across suites, floors, and multiple locations."],
      ["Single Point of Contact", "Eliseo manages your project end to end &mdash; no rotating crews or communication gaps."],
      ], anchor="approach"),
    pricing_section("How Much Does Commercial Interior Painting Cost?",
      "Commercial interior pricing is based on square footage, surface condition, ceiling height, and scheduling needs. Typical Riverview-area ranges:", [
      ["Office Space (per sq ft)", "$1.50 &ndash; $3.50 / sq ft", "Walls; condition and coats dependent"],
      ["Retail / Showroom (per sq ft)", "$2.00 &ndash; $4.00 / sq ft", "Includes detail and brand-color work"],
      ["Single Lobby / Suite Refresh", "$800 &ndash; $2,500", "Walls, trim, and minor repairs"],
      ["Common Areas / Corridors", "Custom Quote", "Multi-zone, height, and access dependent"],
      ], "Ranges are estimates for typical Riverview-area commercial projects. Every commercial job is quoted after a free on-site assessment.",
      cta_text="Request a Commercial Quote"),
    feature_section("Why Choose Us", "Why Riverview Businesses Choose Us", [
      ("Flexible Scheduling", "Evenings, weekends, and phased work so your business never has to close."),
      ("Low-VOC Products", "Occupied-space-safe coatings that protect your team, customers, and patients."),
      ("Single Point of Contact", "Eliseo manages your project from estimate to handover."),
      ("Licensed, Insured, COI", "$1M general liability and workers' comp, with COIs provided on request."),
      ("Brand Color Matching", "Consistent brand colors across suites, floors, and multiple locations."),
    ]),
    gallery_section("Commercial Interior Projects", [
      ("Office Repaint", "Riverview, FL", "Commercial office interior repaint in Riverview FL"),
      ("Retail Buildout", "Brandon, FL", "Retail store interior painting in Brandon FL"),
      ("Medical Office", "Apollo Beach, FL", "Low-VOC medical office interior painting in Apollo Beach FL"),
    ]),
    faq_section("Commercial Interior Painting Questions", _ci_faq),
    related_section("Other Commercial Services", [
      ("/services/commercial-exterior/", "Exterior Commercial Painting", "Storefronts, warehouses, and multi-story buildings built for Florida&rsquo;s climate."),
      ("/services/hoa-multifamily/", "HOA &amp; Multi-Family Painting", "Community-wide programs with coordinated scheduling and consistent color."),
      ("/services/property-management/", "Property Management Programs", "Recurring maintenance and turnover repaints with volume pricing."),
    ]),
    area_callout("Commercial Interior Painting Across South Hillsborough County"),
    cta_banner("Ready to Refresh Your Commercial Interior?", "Get a free, no-obligation commercial estimate. We schedule around your operations and provide COIs on request.", phone_first=True),
  ]),
))

# --------------------------------------------------------------- Commercial Exterior
_ce_crumbs_hero, _ce_crumbs_schema = com_crumbs("Exterior Commercial Painting", f"{BASE}/services/commercial-exterior/")
_ce_faq = [
 ("How much does commercial exterior painting cost?",
  "Commercial exterior pricing depends on building size, height, surface type, and condition. Single-story storefronts often range from $4,000-$10,000, while multi-story and multi-building projects are quoted per square foot after an on-site assessment. Every estimate includes prep, pressure washing, and commercial-grade coatings."),
 ("Can you paint our building without closing it?",
  "Yes. We phase exterior work and schedule around your hours so your business stays open and customers keep their access. We coordinate parking, signage, and entrances with your management to keep the site safe and operational."),
 ("What coatings do you use for Florida commercial exteriors?",
  "We use commercial-grade, UV- and mildew-resistant coatings, including elastomeric and masonry systems for stucco and concrete block. These products waterproof, bridge hairline cracks, and stand up to Tampa Bay's sun, humidity, and storms."),
 ("Can you handle multi-story buildings and high access?",
  "Yes. We have the equipment and experience for multi-story commercial exteriors, including lifts and proper fall protection, and we follow all safety requirements for your property and our crew."),
]
PAGES.append(dict(
  slug="services/commercial-exterior",
  title="Commercial Exterior Painting Riverview FL | Ayala Pro Painting",
  description="Commercial exterior painting in Riverview, FL for storefronts, warehouses & multi-story buildings. Durable, weather-rated coatings for Florida. Free estimates!",
  canonical=f"{BASE}/services/commercial-exterior/",
  schemas=[
    service_schema("Exterior Commercial Painting", "Professional exterior commercial painting for storefronts, warehouses, and multi-story buildings in Riverview, FL.", f"{BASE}/services/commercial-exterior/", "Commercial Exterior Painting"),
    breadcrumb(_ce_crumbs_schema), faqpage(_ce_faq)],
  body="\n\n".join([
    page_hero("Commercial Painting", "Exterior Commercial Painting in Riverview, FL",
      "Ayala Pro Painting delivers professional exterior commercial painting for storefronts, office buildings, warehouses, and multi-story properties throughout Riverview, Florida and the greater Tampa Bay area. Your building&rsquo;s exterior is the first impression customers and tenants get &mdash; and in Florida&rsquo;s climate, it takes a beating from sun, humidity, and storms. We pair commercial-grade, weather-rated coatings with thorough surface preparation and phased scheduling that keeps your business open. Licensed, insured, and owner-operated, we protect your investment and your professional image. Call for a free commercial estimate.",
      _ce_crumbs_hero, phone_first=True),
    signs_section("What We Paint", "Commercial Exteriors Built to Withstand Florida",
      "From a single storefront to a multi-building campus, we coat the exterior surfaces that define your property:",
      ["Storefronts, office buildings, and professional plazas",
       "Stucco, concrete block (CMU), and masonry exteriors",
       "Warehouses, light industrial, and distribution facilities",
       "Multi-story buildings requiring lifts and high access",
       "Parking structures, exterior corridors, and stairwells",
       "Trim, fascia, awnings, bollards, and curb striping"],
      "Commercial building exterior being repainted in Riverview, FL", bg="white"),
    process_section("Our Commercial Exterior Process", [
      ("Site Assessment &amp; Estimate", "We assess surfaces, height and access needs, and timeline constraints, then deliver a written estimate within 48 hours."),
      ("Pressure Wash", "We power wash the entire exterior to remove dirt, chalk, mildew, and loose coatings &mdash; the foundation of a lasting finish."),
      ("Repair &amp; Prep", "We repair stucco cracks, spalling, and damaged surfaces, then caulk and prime bare and repaired areas."),
      ("Phased Application", "We apply commercial-grade, weather-rated coatings in phases scheduled around your operations, keeping entrances and parking accessible."),
      ("Inspection &amp; Handover", "We walk the property with your contact, address punch-list items, and provide warranty documentation."),
    ]),
    table_section("Products &amp; Materials", "Coatings We Use for Florida Commercial Exteriors",
      "We specify commercial-grade systems engineered for Tampa Bay&rsquo;s UV, humidity, and storm exposure.",
      ["Product / System", "Best For", "Why We Use It"], [
      ["Elastomeric Coatings", "Stucco &amp; CMU", "Thick, waterproofing film that bridges hairline cracks and breathes &mdash; ideal for Florida masonry."],
      ["Acrylic Commercial Coatings", "Siding, trim, metal", "UV- and mildew-resistant with strong color retention and durability."],
      ["DTM &amp; Industrial Coatings", "Metal, doors, railings", "Direct-to-metal corrosion protection for high-wear and exposed elements."],
      ], anchor="products"),
    pricing_section("How Much Does Commercial Exterior Painting Cost?",
      "Exterior commercial pricing depends on building size, height, surface type, and condition. Typical Riverview-area ranges:", [
      ["Single-Story Storefront", "$4,000 &ndash; $10,000", "Includes prep, wash, and 2 coats"],
      ["Multi-Story Building (per sq ft)", "$2.00 &ndash; $5.00 / sq ft", "Height and access dependent"],
      ["Warehouse / Industrial", "Custom Quote", "Surface area, substrate, and coating system"],
      ["Trim, Doors &amp; Striping", "Custom Quote", "Add-on or standalone refresh"],
      ], "Ranges are estimates for typical Riverview-area commercial projects. Every commercial job is quoted after a free on-site assessment.",
      cta_text="Request a Commercial Quote"),
    feature_section("Why Choose Us", "Why Riverview Property Owners Choose Us", [
      ("Florida-Grade Coatings", "Elastomeric and commercial systems that waterproof and resist UV, mildew, and storms."),
      ("Phased, Open-for-Business", "We schedule and phase work so your building stays open and accessible."),
      ("High-Access Capability", "Equipment and safety practices for multi-story and hard-to-reach exteriors."),
      ("Licensed, Insured, COI", "$1M general liability and workers' comp, with COIs provided on request."),
      ("Owner Accountability", "Eliseo manages your project from estimate to final inspection."),
    ]),
    gallery_section("Commercial Exterior Projects", [
      ("Storefront Repaint", "Riverview, FL", "Commercial storefront exterior painting in Riverview FL"),
      ("Office Building", "Brandon, FL", "Multi-story office building exterior painting in Brandon FL"),
      ("Warehouse Exterior", "Ruskin, FL", "Warehouse exterior coating in Ruskin FL"),
    ]),
    faq_section("Commercial Exterior Painting Questions", _ce_faq),
    related_section("Other Commercial Services", [
      ("/services/commercial-interior/", "Interior Commercial Painting", "Offices, retail, and medical with low-VOC products and after-hours scheduling."),
      ("/services/hoa-multifamily/", "HOA &amp; Multi-Family Painting", "Community-wide programs with coordinated scheduling and consistent color."),
      ("/services/property-management/", "Property Management Programs", "Recurring maintenance and turnover repaints with volume pricing."),
    ]),
    area_callout("Commercial Exterior Painting Across South Hillsborough County"),
    cta_banner("Ready to Protect and Refresh Your Building?", "Get a free, no-obligation commercial exterior estimate. We phase work around your operations and provide COIs on request.", phone_first=True),
  ]),
))

# --------------------------------------------------------------- HOA & Multi-Family
_hoa_crumbs_hero, _hoa_crumbs_schema = com_crumbs("HOA & Multi-Family Painting", f"{BASE}/services/hoa-multifamily/")
_hoa_faq = [
 ("How do you handle multi-building HOA projects?",
  "We develop a phased schedule that addresses buildings in sequence, coordinating with the HOA board and property manager. Residents receive advance notification, and we maintain consistent color across all buildings using color-matched batches from a single production run."),
 ("Do you coordinate with residents and the board?",
  "Yes. We provide a clear project schedule, post advance notices for affected units, and keep a single point of contact for the board and property manager throughout. Clear communication is what keeps community projects running smoothly."),
 ("Can you match our community's existing color scheme?",
  "Yes. We precisely match your community's approved color palette and maintain consistency across every building and common area. We can also help the board evaluate updated palettes with large-format samples before any community-wide decision."),
 ("Do you provide a certificate of insurance to the HOA?",
  "Absolutely. We carry $1 million in general liability and full workers' compensation coverage and provide certificates of insurance to your HOA board, management company, or developer at no additional charge."),
]
PAGES.append(dict(
  slug="services/hoa-multifamily",
  title="HOA & Multi-Family Painting Riverview FL | Ayala Pro Painting",
  description="HOA & multi-family painting in Riverview, FL. Community-wide programs for townhomes, condos & apartments. Consistent color, coordinated scheduling, HOA compliance. Free estimates!",
  canonical=f"{BASE}/services/hoa-multifamily/",
  schemas=[
    service_schema("HOA and Multi-Family Painting", "Community-wide painting programs for townhomes, condos, and apartment communities in Riverview, FL.", f"{BASE}/services/hoa-multifamily/", "HOA and Multi-Family Painting"),
    breadcrumb(_hoa_crumbs_schema), faqpage(_hoa_faq)],
  body="\n\n".join([
    page_hero("Commercial Painting", "HOA &amp; Multi-Family Painting in Riverview, FL",
      "Ayala Pro Painting runs community-wide painting programs for HOAs, condominium associations, townhome communities, and apartment properties throughout Riverview, Florida and south Hillsborough County. Painting an entire community is a logistics challenge as much as a painting one &mdash; it takes phased scheduling, resident communication, consistent color across every building, and a contractor your board can trust. We coordinate with boards and property managers, keep residents informed, color-match every batch for a uniform look, and provide certificates of insurance on request. Call for a free community assessment.",
      _hoa_crumbs_hero, phone_first=True),
    signs_section("Who We Serve", "Painting Programs for Entire Communities",
      "Whether you oversee a handful of townhome buildings or a large condo community, we have the process to deliver consistent, compliant results:",
      ["Townhome and villa communities",
       "Condominium buildings and mid-rise associations",
       "Apartment complexes and multi-family properties",
       "Clubhouses, pool houses, and amenity buildings",
       "Common areas, breezeways, stairwells, and corridors",
       "Perimeter walls, fences, and community entry features"],
      "Townhome community exterior repaint in Riverview, FL", bg="white"),
    process_section("Our Community Painting Process", [
      ("Board Consultation &amp; Assessment", "We meet with your board or property manager, assess every building, and provide a detailed, phased proposal and timeline."),
      ("Color &amp; Compliance Review", "We confirm your approved palette (or help evaluate a new one with large samples) and document the scope for board approval."),
      ("Resident Communication", "We provide a clear schedule and post advance notices so residents know when work reaches their building and what to expect."),
      ("Phased Application", "We address buildings in sequence with color-matched batches from a single run, keeping access, parking, and amenities usable."),
      ("Board Walkthrough &amp; Handover", "We walk the community with your contact, complete any punch-list items, and provide warranty and maintenance documentation."),
    ]),
    table_section("Our Approach", "What a Community Program Includes",
      "We handle the coordination so your board and residents experience a smooth, professional project.",
      ["Element", "What We Provide"], [
      ["Phased Scheduling", "Buildings addressed in sequence to minimize disruption and maintain access."],
      ["Color Consistency", "Color-matched batches from a single production run across all buildings."],
      ["Resident Notices", "Advance written notifications for affected units and common areas."],
      ["Compliance &amp; COI", "Adherence to community standards plus certificates of insurance for the board."],
      ["Volume Pricing", "Preferred community rates and priority scheduling for ongoing relationships."],
      ], anchor="approach"),
    pricing_section("How Community Painting Pricing Works",
      "HOA and multi-family projects are quoted per community based on building count, surface area, and scope. Typical reference points:", [
      ["Per Building (townhome/condo)", "Custom Quote", "Size, stories, surface type, and condition"],
      ["Common Area / Amenity Building", "Custom Quote", "Clubhouse, pool house, breezeways"],
      ["Community-Wide Program", "Volume Pricing", "Preferred rates for multi-building scope"],
      ["Recurring Maintenance Plan", "Custom Quote", "Scheduled repaints and touch-up programs"],
      ], "Community pricing is developed per project after an on-site assessment with your board or property manager.",
      cta_text="Request a Community Assessment"),
    feature_section("Why Boards Choose Us", "Why HOA Boards &amp; Managers Trust Us", [
      ("Coordinated Scheduling", "Phased plans that keep access, parking, and amenities usable throughout the project."),
      ("Consistent Color", "Color-matched batches ensure every building looks uniform across the community."),
      ("Clear Communication", "A single point of contact and advance resident notices keep everyone informed."),
      ("Licensed, Insured, COI", "$1M general liability and workers' comp, with COIs provided to your board."),
      ("Volume Pricing", "Preferred community rates and priority scheduling for ongoing relationships."),
    ]),
    gallery_section("HOA &amp; Multi-Family Projects", [
      ("Townhome Community", "Riverview, FL", "Townhome community exterior repaint in Riverview FL"),
      ("Condo Building", "Brandon, FL", "Condominium building repaint in Brandon FL"),
      ("Clubhouse &amp; Amenities", "Apollo Beach, FL", "Community clubhouse painting in Apollo Beach FL"),
    ]),
    faq_section("HOA &amp; Multi-Family Painting Questions", _hoa_faq),
    related_section("Other Commercial Services", [
      ("/services/commercial-exterior/", "Exterior Commercial Painting", "Storefronts, warehouses, and multi-story buildings built for Florida&rsquo;s climate."),
      ("/services/commercial-interior/", "Interior Commercial Painting", "Offices, retail, and medical with low-VOC products and after-hours scheduling."),
      ("/services/property-management/", "Property Management Programs", "Recurring maintenance and turnover repaints with volume pricing."),
    ]),
    area_callout("HOA &amp; Multi-Family Painting Across South Hillsborough County"),
    cta_banner("Ready to Plan Your Community&rsquo;s Repaint?", "Get a free, no-obligation community assessment. We coordinate with your board and provide COIs on request.", phone_first=True),
  ]),
))

# --------------------------------------------------------------- Property Management
_pm_crumbs_hero, _pm_crumbs_schema = com_crumbs("Property Management Programs", f"{BASE}/services/property-management/")
_pm_faq = [
 ("Do you offer volume pricing for multiple properties?",
  "Yes. Property management clients with multiple units or properties receive preferred volume pricing and priority scheduling. The more we work together, the better your rates and turnaround &mdash; it's built for ongoing relationships, not one-off jobs."),
 ("How fast can you turn around a unit between tenants?",
  "With priority scheduling, most standard turnover repaints are completed in 1-2 days so you can get units rent-ready fast. We coordinate directly with your team or leasing office to align with move-out and move-in dates."),
 ("Can we set up a recurring maintenance program?",
  "Yes. We build recurring painting maintenance programs tailored to your portfolio &mdash; scheduled exterior refreshes, common-area upkeep, and on-call turnover repaints &mdash; so painting becomes a predictable, managed line item rather than a scramble."),
 ("Do you provide COIs and consolidated invoicing?",
  "Yes. We provide certificates of insurance for each property on request and can consolidate invoicing across your portfolio to simplify your accounting and approvals."),
]
PAGES.append(dict(
  slug="services/property-management",
  title="Property Management Painting Riverview FL | Ayala Pro Painting",
  description="Property management painting programs in Riverview, FL. Turnover repaints, recurring maintenance, volume pricing & priority scheduling for rental portfolios. Free estimates!",
  canonical=f"{BASE}/services/property-management/",
  schemas=[
    service_schema("Property Management Painting Programs", "Recurring painting maintenance and turnover repaints for rental and managed properties in Riverview, FL.", f"{BASE}/services/property-management/", "Property Management Painting"),
    breadcrumb(_pm_crumbs_schema), faqpage(_pm_faq)],
  body="\n\n".join([
    page_hero("Commercial Painting", "Property Management Painting Programs in Riverview, FL",
      "Ayala Pro Painting partners with property managers, landlords, and real estate investors across Riverview, Florida and south Hillsborough County to keep rental and managed properties rent-ready and well-maintained. From fast turnover repaints between tenants to recurring maintenance programs across an entire portfolio, we offer priority scheduling, volume pricing, certificates of insurance, and consolidated invoicing. With a single point of contact in Eliseo and a process built for repeat work, painting becomes a predictable, managed part of your operation. Call to set up your program.",
      _pm_crumbs_hero, phone_first=True),
    signs_section("Who We Serve", "Painting Built for Rental &amp; Managed Portfolios",
      "If you manage properties, you need a painter who is fast, reliable, and easy to work with. Our programs serve:",
      ["Single-family rental portfolios and scattered-site properties",
       "Apartment communities and multi-family buildings",
       "Property management companies and leasing offices",
       "Real estate investors and turnover specialists",
       "Commercial landlords and tenant-improvement projects",
       "Move-in-ready prep and lease-turnover repaints"],
      "Rent-ready unit interior repaint in Riverview, FL", bg="white"),
    process_section("How Our Program Works", [
      ("Portfolio Onboarding", "We learn your properties, standards, and preferred colors, then set up volume pricing and a single point of contact for all requests."),
      ("On-Demand Requests", "Submit a turnover or maintenance request and we schedule it with priority &mdash; coordinated with your move-out and move-in dates."),
      ("Fast, Standardized Repaints", "We use your standard colors and finishes for consistent, rent-ready results across every unit and property."),
      ("Quality Check &amp; Documentation", "We document completed work with photos, provide COIs, and keep your records consistent across the portfolio."),
      ("Consolidated Invoicing", "We streamline approvals and accounting with consolidated invoicing across your properties."),
    ]),
    table_section("Program Benefits", "What Your Program Includes",
      "Everything is structured around speed, predictability, and easy account management.",
      ["Benefit", "What It Means for You"], [
      ["Priority Scheduling", "Your requests jump the queue so units get rent-ready fast."],
      ["Volume Pricing", "Preferred rates that improve as your volume grows."],
      ["Standardized Colors", "Consistent, pre-approved palettes across every property."],
      ["COI &amp; Documentation", "Certificates of insurance and photo documentation on request."],
      ["Consolidated Invoicing", "Simplified approvals and accounting across your portfolio."],
      ], anchor="benefits"),
    pricing_section("How Program Pricing Works",
      "Property management pricing is volume-based and tailored to your portfolio. Typical reference points:", [
      ["Standard Turnover Repaint (per unit)", "$400 &ndash; $1,200", "Unit size, condition, and scope"],
      ["Full Unit Repaint (per unit)", "Custom Quote", "Walls, ceilings, trim, and doors"],
      ["Recurring Maintenance Program", "Volume Pricing", "Scheduled across your portfolio"],
      ["Common Areas &amp; Exteriors", "Custom Quote", "Building-by-building scope"],
      ], "Program pricing is developed for your portfolio after an initial consultation. Volume and recurring clients receive preferred rates.",
      cta_text="Set Up Your Program"),
    feature_section("Why Managers Choose Us", "Why Property Managers Trust Us", [
      ("Fast Turnarounds", "Priority scheduling gets units rent-ready in 1-2 days for standard turnovers."),
      ("Volume Pricing", "Preferred rates that scale with your portfolio and repeat work."),
      ("One Point of Contact", "Eliseo manages every request &mdash; no rotating crews or dropped communication."),
      ("COI &amp; Easy Invoicing", "Certificates of insurance and consolidated invoicing across your properties."),
      ("Consistent Standards", "Pre-approved colors and finishes for a uniform look across every unit."),
    ]),
    gallery_section("Property Management Projects", [
      ("Turnover Repaint", "Riverview, FL", "Rent-ready turnover unit repaint in Riverview FL"),
      ("Apartment Interior", "Brandon, FL", "Apartment interior repaint in Brandon FL"),
      ("Portfolio Maintenance", "Gibsonton, FL", "Recurring maintenance repaint in Gibsonton FL"),
    ]),
    faq_section("Property Management Painting Questions", _pm_faq),
    related_section("Other Commercial Services", [
      ("/services/commercial-interior/", "Interior Commercial Painting", "Offices, retail, and medical with low-VOC products and after-hours scheduling."),
      ("/services/commercial-exterior/", "Exterior Commercial Painting", "Storefronts, warehouses, and multi-story buildings built for Florida&rsquo;s climate."),
      ("/services/hoa-multifamily/", "HOA &amp; Multi-Family Painting", "Community-wide programs with coordinated scheduling and consistent color."),
    ]),
    area_callout("Property Management Painting Across South Hillsborough County"),
    cta_banner("Ready to Streamline Your Painting?", "Set up a property management program with priority scheduling and volume pricing. Call for a free consultation.", phone_first=True),
  ]),
))
